# Generated by Django 5.1.1 on 2024-09-12 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_remove_host_first_name_remove_host_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='host',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='host',
            name='superhost',
        ),
    ]
